"""Initial migration

Revision ID: 18f72d4f708f
Revises: 
Create Date: 2026-02-21 16:41:52.039534

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '18f72d4f708f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('societies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('instagram_handle', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('scrape_posts', sa.Boolean(), nullable=True),
    sa.Column('scrape_stories', sa.Boolean(), nullable=True),
    sa.Column('last_post_check', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_story_check', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_societies_instagram_handle'), 'societies', ['instagram_handle'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('whatsapp_verified', sa.Boolean(), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.Column('notification_preferences', postgresql.JSONB(astext_type=sa.Text()), server_default='{"whatsapp": true, "email": true}', nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.create_table('events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('society_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('location_building', sa.String(length=100), nullable=True),
    sa.Column('location_room', sa.String(length=50), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_type', sa.String(length=20), nullable=True),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('extracted_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notified', sa.Boolean(), nullable=True),
    sa.Column('notification_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['society_id'], ['societies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_is_active'), 'events', ['is_active'], unique=False)
    op.create_index(op.f('ix_events_notified'), 'events', ['notified'], unique=False)
    op.create_index(op.f('ix_events_start_time'), 'events', ['start_time'], unique=False)
    op.create_table('posts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('society_id', sa.UUID(), nullable=True),
    sa.Column('instagram_post_id', sa.String(length=255), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('media_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_free_food', sa.Boolean(), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['society_id'], ['societies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posts_detected_at'), 'posts', ['detected_at'], unique=False)
    op.create_index(op.f('ix_posts_instagram_post_id'), 'posts', ['instagram_post_id'], unique=True)
    op.create_index(op.f('ix_posts_is_free_food'), 'posts', ['is_free_food'], unique=False)
    op.create_index(op.f('ix_posts_processed'), 'posts', ['processed'], unique=False)
    op.create_table('scraping_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('society_id', sa.UUID(), nullable=True),
    sa.Column('scrape_type', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('items_found', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['society_id'], ['societies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scraping_logs_created_at'), 'scraping_logs', ['created_at'], unique=False)
    op.create_table('stories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('society_id', sa.UUID(), nullable=True),
    sa.Column('story_text', sa.Text(), nullable=True),
    sa.Column('story_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_free_food', sa.Boolean(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('screenshot_url', sa.Text(), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['society_id'], ['societies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stories_content_hash'), 'stories', ['content_hash'], unique=True)
    op.create_index(op.f('ix_stories_detected_at'), 'stories', ['detected_at'], unique=False)
    op.create_index(op.f('ix_stories_is_free_food'), 'stories', ['is_free_food'], unique=False)
    op.create_index(op.f('ix_stories_processed'), 'stories', ['processed'], unique=False)
    op.create_table('user_society_preferences',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('society_id', sa.UUID(), nullable=False),
    sa.Column('notify', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['society_id'], ['societies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'society_id')
    )
    op.create_table('notification_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('notification_type', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_logs_sent_at'), 'notification_logs', ['sent_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_logs_sent_at'), table_name='notification_logs')
    op.drop_table('notification_logs')
    op.drop_table('user_society_preferences')
    op.drop_index(op.f('ix_stories_processed'), table_name='stories')
    op.drop_index(op.f('ix_stories_is_free_food'), table_name='stories')
    op.drop_index(op.f('ix_stories_detected_at'), table_name='stories')
    op.drop_index(op.f('ix_stories_content_hash'), table_name='stories')
    op.drop_table('stories')
    op.drop_index(op.f('ix_scraping_logs_created_at'), table_name='scraping_logs')
    op.drop_table('scraping_logs')
    op.drop_index(op.f('ix_posts_processed'), table_name='posts')
    op.drop_index(op.f('ix_posts_is_free_food'), table_name='posts')
    op.drop_index(op.f('ix_posts_instagram_post_id'), table_name='posts')
    op.drop_index(op.f('ix_posts_detected_at'), table_name='posts')
    op.drop_table('posts')
    op.drop_index(op.f('ix_events_start_time'), table_name='events')
    op.drop_index(op.f('ix_events_notified'), table_name='events')
    op.drop_index(op.f('ix_events_is_active'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_societies_instagram_handle'), table_name='societies')
    op.drop_table('societies')
    # ### end Alembic commands ###